apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: default-namespace-gateway
  namespace: default
spec:
  gatewayClassName: haproxy-ingress-gatewayclass
  listeners:
    - allowedRoutes:
        namespaces:
          from: All
      name: webhook
      port: 8000
      protocol: HTTP
